### ISSUE TITLE
[Request] Magnet Hotkey, Bauble, configurable range

### ISSUE THREAD

**Issue by jedirulez** [FantasyTeddy/QuantumFlux#1]
As requested on the reddit post I have created this issue for the request of features for the Magnet in QuantumFlux.

The reasons I loved the Practicalities and then the QuantumFlux magnet were mainly two-fold: It instantly moved the items into the inventory of the player (no animation of the items slowly sucking in). Also it was one of the only magnets that also worked with XP orbs (again immediately going to the player).

1. I believe QuantumFlux already has a hotkey for the Magnet, continuing this would be great
2. Adding the ability to put the Magnet in a Bauble slot, ideally ANY slot
3. At some point the config file had range options for the Magnet, but not sure they worked. Could perhaps introduce upgraded magnets as opposed to the config options? 
4. I don't remember if QuantumFlux included this as well, but a block that can be placed in-world to disable the affects of the magnet, similar to the Solegnolia from Botania. Ideally the block could be controlled via a redstone signal.

Thanks!

**Comment by FantasyTeddy** [comment]
Thank you for your suggestions. I will keep them in mind whenever I get around doing some more in depth work.

**Comment by TheUnderTaker11** [comment]
@jedirulez Not to self advertise, but I have a [Better Magnets](https://minecraft.curseforge.com/projects/better-magnets) mod, which actually uses the same code as this mod's magnet, but works as bauble, has multiple tiers, configurable range for each tier, a block to stop items from being sucked up in an area above/below it, and an item that turns off the magnet if it's in a player's inventory. (Also just like this mod it has a hotkey, but you will get an indicator in chat for if you enabled or disabled the magnet.)        

Obviously, since I made it I would suggest using it, I always loved quantumflux/practicalities magnets as well! Whole reason for making the mod.

**Comment by FantasyTeddy** [comment]
Great to see someone else being inspired by QuantumFlux/Practicalities.
But I don't quite get the intention of your comment, because all you did was in fact advertise your mod and not giving me any valuable feedback for this mod.

**Comment by TheUnderTaker11** [comment]
I am giving the person an option for literally exactly what they are looking for.
Trust me if GitHub had direct messages I would have done that.

**Comment by TheUnderTaker11** [comment]
Baubles for the magnet have been added, and a chat message now pops up when toggling the magnet, added in #19 . (Whenever that get implemented and uploaded.)

A block to cancel the magnet can be gotten by using the [Demagnatize](https://minecraft.curseforge.com/projects/demagnetize) mod, and it has a lot of features that wouldn't be included with a built-in magnet canceling block!         

So all the suggestions have been added besides magnet tiers.

**Comment by FantasyTeddy** [comment]
Thanks @TheUnderTaker11 for your contributions!
I will close this feature request now, because everything has been added to the magnet that I wanted to have.
